# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtlanAT0110 < Formula
  desc "Atlan CLI"
  homepage "https://developer.atlan.com/sdks/cli/?h=cli"
  version "0.1.10"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/rittikdasgupta/releases/releases/download/v0.1.10/atlan_Darwin_amd64.tar.gz"
      sha256 "73465af41b6844c66f58cb25aa7593b781211d5462b7dbc6437a39b8734560aa"

      def install
        bin.install "atlan"
      end
    end
    on_arm do
      url "https://github.com/rittikdasgupta/releases/releases/download/v0.1.10/atlan_Darwin_arm64.tar.gz"
      sha256 "0b89d7cddf1c560f150b167ab76ec04aeb72606129865f65102232692574024a"

      def install
        bin.install "atlan"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rittikdasgupta/releases/releases/download/v0.1.10/atlan_Linux_amd64.tar.gz"
        sha256 "3ef2acc0ca433fea956dd2f8d1a2cb13eada639aac1e7c5117a6e3dc8a9e78c6"

        def install
          bin.install "atlan"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rittikdasgupta/releases/releases/download/v0.1.10/atlan_Linux_arm64.tar.gz"
        sha256 "72616e8fac04a070539aefc2c553d925d07954f14c9afacd3af1a7ec9035243a"

        def install
          bin.install "atlan"
        end
      end
    end
  end

  def post_install
    system "#{bin}/atlan"
  end
end
