# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtlanAT020 < Formula
  desc "Atlan CLI"
  homepage "https://developer.atlan.com/sdks/cli"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/rittikdasgupta/releases/releases/download/v0.2.0/atlan_Darwin_amd64.tar.gz"
      sha256 "b78b9ef77d9ed77eddde31a09bccda7d86eaadb1485d39cc6ab5653ddee5140f"

      def install
        bin.install "atlan"
      end
    end
    on_arm do
      url "https://github.com/rittikdasgupta/releases/releases/download/v0.2.0/atlan_Darwin_arm64.tar.gz"
      sha256 "6d92a19c653d176369a5f1f4fd73b8bc7cc49f9245a530236229ac64b263079e"

      def install
        bin.install "atlan"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rittikdasgupta/releases/releases/download/v0.2.0/atlan_Linux_amd64.tar.gz"
        sha256 "3e733c27ebc33e222c256c10020386349446d7f453c829105e2e78ee311306ed"

        def install
          bin.install "atlan"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rittikdasgupta/releases/releases/download/v0.2.0/atlan_Linux_arm64.tar.gz"
        sha256 "dc5fe3ac3103bf4ecfcbfcddbe28a433455b8a115ba804e35a520dae962bc7b0"

        def install
          bin.install "atlan"
        end
      end
    end
  end

  def post_install
    system "#{bin}/atlan"
  end
end
