# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtlanAT017 < Formula
  desc "Atlan CLI"
  homepage "https://developer.atlan.com/sdks/cli/?h=cli"
  version "0.1.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/rittikdasgupta/releases/releases/download/v0.1.7/atlan_Darwin_amd64.tar.gz"
      sha256 "a42b397be232a804e10ea5eeedeb1a8d1ed65d78440a9f9612f3c67a73caf450"

      def install
        bin.install "atlan"
      end
    end
    on_arm do
      url "https://github.com/rittikdasgupta/releases/releases/download/v0.1.7/atlan_Darwin_arm64.tar.gz"
      sha256 "c20c36605a75cefda0d44ca768ee07fd6a2efe0837111bbd4589bb38e9bce8f5"

      def install
        bin.install "atlan"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rittikdasgupta/releases/releases/download/v0.1.7/atlan_Linux_amd64.tar.gz"
        sha256 "f4e86a4d8c27c7976080d10164fd25463ac9d591057b4b9e2834f3ec8b3ea402"

        def install
          bin.install "atlan"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rittikdasgupta/releases/releases/download/v0.1.7/atlan_Linux_arm64.tar.gz"
        sha256 "27e14ac944fd4b01c64768dfb43c9928302cdf809f4500994cbfec54a3626648"

        def install
          bin.install "atlan"
        end
      end
    end
  end

  def post_install
    system "#{bin}/atlan"
  end
end
