# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtlanAT022 < Formula
  desc "Atlan CLI"
  homepage "https://developer.atlan.com/sdks/cli"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/rittikdasgupta/releases/releases/download/v0.2.2/atlan_Darwin_amd64.tar.gz"
      sha256 "c9b4f035887fd8d90a6f8bb0972bb684ca37e6236b7847876bfb069193cb0a27"

      def install
        bin.install "atlan"
      end
    end
    on_arm do
      url "https://github.com/rittikdasgupta/releases/releases/download/v0.2.2/atlan_Darwin_arm64.tar.gz"
      sha256 "a220f59f4b3ddd77e80aa1ebf3816286e1ee19e6d9c169668627263cd3d79283"

      def install
        bin.install "atlan"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rittikdasgupta/releases/releases/download/v0.2.2/atlan_Linux_amd64.tar.gz"
        sha256 "5e7faeb8ddffe04d79057daf72c8a8326c1634c3f2b17e4b8f82d0fd772b6394"

        def install
          bin.install "atlan"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rittikdasgupta/releases/releases/download/v0.2.2/atlan_Linux_arm64.tar.gz"
        sha256 "34304d2a2404768a356a8dcfb3c78ae0a1ba479a6998e4a59cf10bfc04867bc1"

        def install
          bin.install "atlan"
        end
      end
    end
  end

  def post_install
    system "#{bin}/atlan"
  end
end
